version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ../:/mnt/locust
    command: -f /mnt/locust/locust_demo.py --master -H http://master:8089
  
  worker:
    image: locustio/locust
    volumes:
      - ../:/mnt/locust
    command: -f /mnt/locust/locust_demo.py --worker --master-host master
